<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\AdminViews\**" />
    <EmbeddedResource Remove="Views\AdminViews\**" />
    <None Remove="Views\AdminViews\**" />
    <Page Remove="Views\AdminViews\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\**\*.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SharedLibrary\SharedLibrary.csproj" />
    <ProjectReference Include="..\AndersonsBakeryAPI\AndersonsBakeryAPI.csproj" />
  </ItemGroup>

</Project>
