CREATE TABLE [dbo].[User]
(
    [Id]        INT NOT NULL PRIMARY KEY IDENTITY,
    [Username]  NVARCHAR(50)  NOT NULL,
    [Password]  NVARCHAR(100) NOT NULL,
    [Role]      NVARCHAR(50)  NOT NULL,
    [DateAdded] DATETIME NOT NULL DEFAULT GETDATE()
);